spring.application.name=backends

# Datasource (2048)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Weather API keys
google.geocoding.api.key=${GOOGLE_GEOCODING_API_KEY}
google.weather.api.key=${GOOGLE_WEATHER_API_KEY}

# Server
server.port=${PORT:8080}